name: Lobby-System
version: 1.0
main: SoartexHD\Main
api: [3.0.0-ALPHA12]
author: HummelSvem
permissions:
  lobby.yt:
    default: op
commands:
  hub:
     description: hub
     usage: /hub
  lobby:
     description: lobby
     usage: /lobby